# Generated by Django 3.0 on 2020-12-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelpPsc', '0004_psc_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psc',
            name='category',
        ),
    ]
