# Generated by Django 3.0 on 2020-12-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpPsc', '0010_psc_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psc',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
