# Generated by Django 3.0 on 2020-12-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpPsc', '0011_auto_20201202_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psc',
            name='question',
            field=models.CharField(max_length=1000),
        ),
    ]
