# Generated by Django 3.0 on 2020-12-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpPsc', '0012_auto_20201203_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psc',
            name='apple',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='psc',
            name='boy',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='psc',
            name='cat',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='psc',
            name='dog',
            field=models.CharField(max_length=300),
        ),
    ]
